# Generated by Django 4.1.5 on 2023-01-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jop',
            fields=[      # primary key (ينشئ مع كل ملف الا لو غيرته وانا بنشئ المودل)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
