# Generated by Django 4.1.5 on 2023-01-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jop_jop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='Published_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jop',
            name='Vacancy',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jop',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jop',
            name='experience',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jop',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
