# Generated by Django 3.2.16 on 2023-01-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20230124_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=' ', upload_to='jobs/'),
            preserve_default=False,
        ),
    ]
